apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: darqko/spring-boot-kubernetes-aut
      docker:
        dockerfile: Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - k8s.yml
