spring:
  cloud:
    kubernetes:
      config:
        enabled: true
        sources:
          - namespace: mga
            name: spring-boot-kubernetes
      reload:
        enabled: true
        mode: event
        strategy: refresh